clear all; clc; close all;
M = 2;
K = 10^(6/10);
DIVORDER = 1;
EbN0 = 0:0.1:20;
BER_Ray = berfading(EbN0,'dpsk',M,DIVORDER);
BER_Rician = berfading(EbN0,'dpsk',M,1,K);
semilogy(EbN0, BER_Ray);
hold on;
semilogy(EbN0, BER_Rician);
hold on;
grid on;
ylim([10^-5 1]);
legend('Rayleigh Channel','Rician Channel');
xlabel('SNR (dB)');
ylabel('BiT Error Rate');
title('DPSK BER Vs SNR for K = 0 dB');

figure(2)
K2 = 10^(10/10);
DIVORDER = 1;
EbN0 = 0:0.1:50;
BER_Ray2 = berfading(EbN0,'dpsk',M,DIVORDER);
BER_Rician2 = berfading(EbN0,'dpsk',M,1,K2);
semilogy(EbN0, BER_Ray2);
hold on;
semilogy(EbN0, BER_Rician2);
hold on;
grid on;
ylim([10^-5 1]);
legend('Rayleigh Channel','Rician Channel');
xlabel('SNR (dB)');
ylabel('Bit Error Rate');
title('DPSK BER Vs SNR for K = 10 dB');
